import { Order } from '../types';

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    order_number: '#001',
    table_id: 'table-1',
    table_number: 'A1',
    status: 'pending',
    items: [
      {
        id: 'item-order-1',
        order_id: 'order-1',
        menu_item_id: 'item-1',
        menu_item_name: 'ข้าวผัดไก่',
        quantity: 2,
        price: 60,
        notes: 'ไม่เผ็ด',
      },
      {
        id: 'item-order-2',
        order_id: 'order-1',
        menu_item_id: 'item-23',
        menu_item_name: 'ชาร้อน',
        quantity: 1,
        price: 25,
        notes: '',
      },
    ],
    total_amount: 145,
    notes: 'Table ordering',
    mode: 'restaurant',
    created_at: '2025-02-23T10:00:00Z',
    updated_at: '2025-02-23T10:00:00Z',
  },
  {
    id: 'order-2',
    order_number: '#002',
    table_id: 'table-2',
    table_number: 'A2',
    status: 'confirmed',
    items: [
      {
        id: 'item-order-3',
        order_id: 'order-2',
        menu_item_id: 'item-9',
        menu_item_name: 'ส้มตำไก่',
        quantity: 1,
        price: 65,
        notes: '',
      },
      {
        id: 'item-order-4',
        order_id: 'order-2',
        menu_item_id: 'item-2',
        menu_item_name: 'ข้าวผัดกุ้ง',
        quantity: 1,
        price: 80,
        notes: 'เพิ่มพริก',
      },
    ],
    total_amount: 145,
    notes: '',
    mode: 'restaurant',
    created_at: '2025-02-23T10:15:00Z',
    updated_at: '2025-02-23T10:20:00Z',
  },
  {
    id: 'order-3',
    order_number: '#003',
    status: 'preparing',
    items: [
      {
        id: 'item-order-5',
        order_id: 'order-3',
        menu_item_id: 'item-17',
        menu_item_name: 'ไก่ทอด',
        quantity: 1,
        price: 75,
        notes: '',
      },
      {
        id: 'item-order-6',
        order_id: 'order-3',
        menu_item_id: 'item-22',
        menu_item_name: 'กาแฟนม',
        quantity: 2,
        price: 40,
        notes: '',
      },
    ],
    total_amount: 155,
    customer_name: 'สมิทธ์',
    customer_phone: '0891234567',
    notes: 'Market mode queue',
    mode: 'market',
    queue_number: 5,
    tracking_url: '/customer/track/order-3',
    created_at: '2025-02-23T10:30:00Z',
    updated_at: '2025-02-23T10:35:00Z',
  },
  {
    id: 'order-4',
    order_number: '#004',
    table_id: 'table-3',
    table_number: 'A3',
    status: 'ready',
    items: [
      {
        id: 'item-order-7',
        order_id: 'order-4',
        menu_item_id: 'item-13',
        menu_item_name: 'แกงเขียวหวาน',
        quantity: 2,
        price: 75,
        notes: '',
      },
    ],
    total_amount: 150,
    notes: '',
    mode: 'restaurant',
    created_at: '2025-02-23T10:45:00Z',
    updated_at: '2025-02-23T11:00:00Z',
  },
  {
    id: 'order-5',
    order_number: '#005',
    status: 'completed',
    items: [
      {
        id: 'item-order-8',
        order_id: 'order-5',
        menu_item_id: 'item-33',
        menu_item_name: 'หมูปิ้ง',
        quantity: 1,
        price: 80,
        notes: '',
      },
    ],
    total_amount: 80,
    customer_name: 'สมศรี',
    customer_phone: '0892345678',
    notes: '',
    mode: 'market',
    queue_number: 1,
    tracking_url: '/customer/track/order-5',
    created_at: '2025-02-23T09:00:00Z',
    updated_at: '2025-02-23T09:15:00Z',
  },
  {
    id: 'order-6',
    order_number: '#006',
    status: 'cancelled',
    items: [
      {
        id: 'item-order-9',
        order_id: 'order-6',
        menu_item_id: 'item-19',
        menu_item_name: 'ปลาทอด',
        quantity: 1,
        price: 90,
        notes: '',
      },
    ],
    total_amount: 90,
    customer_name: 'สมชาย',
    customer_phone: '0893456789',
    notes: 'ยกเลิกเพราะเปลี่ยนใจ',
    mode: 'market',
    queue_number: 3,
    tracking_url: '/customer/track/order-6',
    created_at: '2025-02-23T08:30:00Z',
    updated_at: '2025-02-23T08:45:00Z',
  },
  {
    id: 'order-7',
    order_number: '#007',
    table_id: 'table-4',
    table_number: 'A4',
    status: 'pending',
    items: [
      {
        id: 'item-order-10',
        order_id: 'order-7',
        menu_item_id: 'item-31',
        menu_item_name: 'ปาท่าคาโบโนรา่',
        quantity: 1,
        price: 85,
        notes: '',
      },
      {
        id: 'item-order-11',
        order_id: 'order-7',
        menu_item_id: 'item-26',
        menu_item_name: 'น้ำมะพร้าว',
        quantity: 1,
        price: 35,
        notes: '',
      },
    ],
    total_amount: 120,
    notes: '',
    mode: 'restaurant',
    created_at: '2025-02-23T11:00:00Z',
    updated_at: '2025-02-23T11:00:00Z',
  },
  {
    id: 'order-8',
    order_number: '#008',
    status: 'confirmed',
    items: [
      {
        id: 'item-order-12',
        order_id: 'order-8',
        menu_item_id: 'item-34',
        menu_item_name: 'ไก่ย่าง',
        quantity: 2,
        price: 70,
        notes: '',
      },
      {
        id: 'item-order-13',
        order_id: 'order-8',
        menu_item_id: 'item-25',
        menu_item_name: 'น้ำส้ม',
        quantity: 2,
        price: 25,
        notes: '',
      },
    ],
    total_amount: 190,
    customer_name: 'ภูมี',
    customer_phone: '0894567890',
    notes: '',
    mode: 'market',
    queue_number: 6,
    tracking_url: '/customer/track/order-8',
    created_at: '2025-02-23T11:15:00Z',
    updated_at: '2025-02-23T11:20:00Z',
  },
  {
    id: 'order-9',
    order_number: '#009',
    table_id: 'table-5',
    table_number: 'A5',
    status: 'preparing',
    items: [
      {
        id: 'item-order-14',
        order_id: 'order-9',
        menu_item_id: 'item-6',
        menu_item_name: 'ก๋วยเตี๋ยวไก่มาดแกง',
        quantity: 1,
        price: 50,
        notes: '',
      },
    ],
    total_amount: 50,
    notes: '',
    mode: 'restaurant',
    created_at: '2025-02-23T11:30:00Z',
    updated_at: '2025-02-23T11:35:00Z',
  },
  {
    id: 'order-10',
    order_number: '#010',
    status: 'ready',
    items: [
      {
        id: 'item-order-15',
        order_id: 'order-10',
        menu_item_id: 'item-36',
        menu_item_name: 'ตับหมูทอด',
        quantity: 1,
        price: 65,
        notes: '',
      },
    ],
    total_amount: 65,
    customer_name: 'นดา',
    customer_phone: '0895678901',
    notes: '',
    mode: 'market',
    queue_number: 2,
    tracking_url: '/customer/track/order-10',
    created_at: '2025-02-23T11:45:00Z',
    updated_at: '2025-02-23T12:00:00Z',
  },
];
